### ISSUE TITLE
Game crashes when clearing game data

### ISSUE THREAD

**Issue by XEN0PHIL** [Anuken/Mindustry#2706]
**Platform**: Windows

**Build**: BE 9937

**Issue**: Attempting to **clear game data** crashes the game.

**Steps to reproduce**: 
1. Launch Mindustry BE 9937;
2. Navigate to  Settings -> Game Data -> Clear Game Data...;
3. Press OK.

**Crash report**: [crash-report-09_24_2020_18_55_38.txt](https://github.com/Anuken/Mindustry/files/5277504/crash-report-09_24_2020_18_55_38.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
fixed

**Comment by XEN0PHIL** [comment]
> fixed

@Anuken It's still happening in BE 9940
[crash-report-09_24_2020_19_41_21.txt](https://github.com/Anuken/Mindustry/files/5277737/crash-report-09_24_2020_19_41_21.txt)

**Comment by Anuken** [comment]
Fixed, not pushed.
