### ISSUE TITLE
Cryomixer the water-void

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry#2831]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *Steam Build 107*

**Issue**: 
*The Cryomixer in combination with a Thorium (Impact) Reactor consumes all the water it gets (max 12water/s per mixer). It doesnt matter if I use only 1 Water Extractor or 100 while the Reactor* **should only consume 2.4 cryo/sec.**
*The titanium consumption seems nominal. (tested in another build)

*The bigger build runs with -2K power in total and* **non of the Water Extractors backup water** *while it drills like 60water/s.
You can also see that the small build only provides* **660 Power**
**Reactor +900
Watex Extractor - 2 x 90
Cryo Mixer - 60**
*Theoretical total max Power consumption of Extractor and Mixer only ~45 Power
And its a big difference if I get only* **660 Power or 855 power** *at best.
And guys, please dont come with the answer "just use pumps", thats not the issue here.*

*Also this water Issue is the reason why some Reactor Schematics wont work probably due to missing water even if the numbers are all correct.*

**How it should be:** 
*The Thorium Reactor consumes 2.4cryo/sec, therefor a single Water Extractor should only drill 2.4water/s as well and backup water at some point. Power consumption should be equall to water drillspeed. Same behavior with Impact Reactors*

**Steps to reproduce**: 
![image](https://user-images.githubusercontent.com/66265700/95018321-44bf9c80-065f-11eb-9cef-d51306dc2c48.png)

**Link(s) to mod(s) used**: *---*

**Save file**: *---*

**Crash report**: *---*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
*(at least nothing that got fixed)*

**Comment by potatoisagender** [comment]
design needs to be more compact

/s

**Comment by Anuken** [comment]
> Save file: ---

**Save files are required.**

**Comment by Absolute359** [comment]
Safefile

[Water Void.zip](https://github.com/Anuken/Mindustry/files/5323444/Water.Void.zip)

**Comment by potatoisagender** [comment]
perhaps it has to do with junctions?

**Comment by Absolute359** [comment]
Junctions don't causes this issue,
they are only to extend here.

**Comment by Anuken** [comment]
(fixed)

**Comment by Absolute359** [comment]
thanks

**Comment by claw4oo** [comment]
Issue is still present in Steam Build 109



In these setups, 
the left one is producing + 670-680 energy/s
Right one is producing 760-770 energy/s

Both of these setups use the same amount of cryofluid, but have a power difference of approx 90/s,  about the same as one water extractor

What should happen is that both of these setups produce the same amount of power, greater than what is shown.

20% of the cryo mixer is used
-12 energy/s instead of 60/s
36%~ of the water extractor is used, so it  should draw 
-32~ energy/s, instead of 90/s
+900 e/s comes from the generator
Meaning that both setups should be generating around 
856~ energy/s rather than 770

An additional bug that may or may not be related, is that cryofluid mixers take 30 energy/s when given titanium but no water, outputting 0 cryofluid.


Picture

[https://cdn.discordapp.com/attachments/396416151032299521/768064881894096936/unknown.png](url)

Savefile

[cryofluidpowerandwaterdrain.zip](https://github.com/Anuken/Mindustry/files/5412361/cryofluidpowerandwaterdrain.zip)

**Comment by Anuken** [comment]
> 20% of the cryo mixer is used
> -12 energy/s instead of 60/s

Blocks are not supposed to consume energy in proportion to their utilization. Even if a block is only at ~20% production capacity, it will not be consuming power at a 20% rate.

**Comment by claw4oo** [comment]
Would that also count for the power used over a certain period of time? For example, the water extractor in this example is completely being used, rather than spending some ticks idling using no power.

**Comment by claw4oo** [comment]
Issue is still present in build 221

Cryofluid mixers still eat 100% of the water used, despite not needing it all

For example, 1 water extractor, 1 cryo, and 1 thorium reactor will result in always losing water.
