### ISSUE TITLE
IOS Mindustry sounds stop when game is interrupted by a call or timer

### ISSUE THREAD

**Issue by LampbuIb** [Anuken/Mindustry#7866]
**Platform**: IOS

**Build**: 140.2
**Issue**: When the game is interrupted by a timer or a call, after the timer or call has been stopped, all in game sounds stop. Have reinstalled game, no change. Have experienced this issue over a few weeks now, affects the whole game, when exporting data to desktop, such issue is not present.

**Steps to reproduce**: Play mindustry on IOS, interrupt your game by calling yourself or setting a timer, notice that all sounds are gone until game is restarted 

**Link(s) to mod(s) used**: N/A; sounds still stop regardless of mods

**Save file**: 
[save-Maze Nov 10 11:10.zip](https://github.com/Anuken/Mindustry/files/9986961/save-Maze.Nov.10.11.10.zip)
To be clear, I am 99.9% sure that this is **not** related to a save, it does this regardless of map, I just launched a quick game and set a short timer, it is very likley that the sounds on this save will work until you interrupt the game too, just putting a save in just in case, dont reap my soul I kind of need it rn

**(Crash) logs**: No crash.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [testflight > v140.2, this is the latest version I can get sorry] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Fixed in Arc.

**Comment by damonLL** [comment]
This issue persists. Running on iOS 17.0.2, iPhone 12 Pro. Mindustry release build 146.

Anytime an iOS alarm pops up, the game has no sound from that point. Requires exit and restart.

**Comment by Anuken** [comment]
The bug was marked as fixed upstream in the sound library I use (miniaudio); if that is not the case, it won't be getting fixed.
