### ISSUE TITLE
Unable to import data on iOS

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#887]
**Platform**: iOS (13.1.12, iPhone 11 pro max)

**Build**: release build 98 (5.1)

**Issue**: Importing game data does not work.

**Steps to reproduce**: Export game data that has progress, relaunch game, wipe game data, import exported game data, relaunch game, no progress in game data.

An alternative method to importing: start a custom game, exit the game, export the save in the “load game” menu, delete the save in the “load game” menu, and import the save using in the “load game” menu.  When the app is relaunched the imported save is not present in the list of imported games.

**Comment by Anuken** [comment]
Should be fixed next release.

**Comment by willis936** [comment]
I can confirm that the issue still exists for both import methods in iOS 13.2, release build 99.1 (5.1.1)

**Comment by soulan** [comment]
Hey, I have the same issue, but I got some informations
```
standard	09:45:40.783796 +0100	kernel	Sandbox: 2 duplicate reports for com.apple.Docume deny(1) file-issue-extension target:/private/var/mobile/Containers/Shared/AppGroup/805464E7-3999-46CE-AF6D-6C13B92B664C/File Provider Storage/mindustry/mindustry.zip class:com.apple.app-sandbox.read-write
fehler	09:45:40.783839 +0100	kernel	Sandbox: IOSLauncher(28866) deny(1) file-read-metadata /private/var/mobile/Containers/Shared/AppGroup/805464E7-3999-46CE-AF6D-6C13B92B664C/File Provider Storage/mindustry/mind.zip
```
https://stackoverflow.com/questions/33513608/app-sandboxing-issue-with-apple-mac-app-store

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentInteraction_TopicsForIOS/Articles/RegisteringtheFileTypesYourAppSupports.html#//apple_ref/doc/uid/TP40010411-SW1

this could also help.

@Anuken If testing is an issue, I might be able to help. I have a phone, developer profile and mac so I can test things for you or we figure something out if you want or have anything in your head how that would work

**Comment by Anuken** [comment]
I obtained an iOS device a few days ago, and after some testing the errors turns out to be:
> The file couldn't be opened because you don't have permission to view it.

**Comment by Anuken** [comment]
44fdda09c660ce68683cc4f9a3f7de85db21dfa4

**Comment by soulan** [comment]
can confirm that it works now 👍 great job thanks :)
